import { inviaOperazioneRentri, emissioneFir, firmaRicezione } from "@/lib/rentriVpsApi";
let logEntries = [];
let logListeners = [];
function addLog(entry) { const full = { ...entry, id: crypto.randomUUID(), timestamp: new Date().toISOString() }; logEntries = [full, ...logEntries].slice(0, 200); logListeners.forEach((fn) => fn()); return full; }
export function subscribeToLogs(fn) { logListeners.push(fn); return () => { logListeners = logListeners.filter((l) => l !== fn); }; }
export function getLogs() { return logEntries; }
export async function healthCheck() { try { const res = await inviaOperazioneRentri({ cliente: "global", tipo_operazione: "LISTA_BLOCCHI", payload: {} }); return { ok: res.success, status: res.status }; } catch { return { ok: false, status: 0 }; } }
export async function richiestaVidimazione(societaId, quantita) { const res = await inviaOperazioneRentri({ cliente: societaId.toLowerCase(), tipo_operazione: "VIDIMAZIONE", payload: { quantita } }); const entry = addLog({ endpoint: "[VPS] VIDIMAZIONE", tenant: societaId, status: res.status, success: res.success, response: res.data, request: { quantita } }); return { ok: res.success, status: res.status, data: res.data, logEntry: entry }; }
export async function firmaFirProduttore(societaId, firData) { const res = await emissioneFir(societaId.toLowerCase(), firData); const entry = addLog({ endpoint: "[VPS] FIR_EMISSIONE", tenant: societaId, status: res.status, success: res.success, response: res.data, request: firData }); return { ok: res.success, status: res.status, data: res.data, logEntry: entry }; }
export async function firmaFirDestinatario(societaId, firData) { const res = await firmaRicezione(societaId.toLowerCase(), firData); const entry = addLog({ endpoint: "[VPS] FIRMA_RICEZIONE", tenant: societaId, status: res.status, success: res.success, response: res.data, request: firData }); return { ok: res.success, status: res.status, data: res.data, logEntry: entry }; }
export async function registroCarico(societaId, payload) { const res = await inviaOperazioneRentri({ cliente: societaId.toLowerCase(), tipo_operazione: "REGISTRO", payload: { movimenti: [{ tipo: "carico", ...payload }] } }); const entry = addLog({ endpoint: "[VPS] REGISTRO", tenant: societaId, status: res.status, success: res.success, response: res.data, request: payload }); return { ok: res.success, status: res.status, data: res.data, logEntry: entry }; }
export async function registroScarico(societaId, payload) { const res = await inviaOperazioneRentri({ cliente: societaId.toLowerCase(), tipo_operazione: "REGISTRO", payload: { movimenti: [{ tipo: "scarico", ...payload }] } }); const entry = addLog({ endpoint: "[VPS] REGISTRO", tenant: societaId, status: res.status, success: res.success, response: res.data, request: payload }); return { ok: res.success, status: res.status, data: res.data, logEntry: entry }; }
export function downloadCSV(numbers, filename) { const csv = "numero_fir\n" + numbers.join("\n"); const blob = new Blob([csv], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); }
