import { inviaOperazioneRentri, emissioneFir, firmaRicezione, richiestaVidimazione, scaricaPdfLotto } from "@/lib/rentriVpsApi";
const TENANT_MAP = { "167d07ad-9184-484e-85a6-da5ceafa42a3": "global", "dc2a6046-d9a8-4549-8e45-82367d695ac6": "multy" };
const MN_CONTEXT_MAP = { multyproget: "multy", "multyproget-intermediario": "multy", "multyproget-impianto": "multy", niyol: "niyol" };
export function resolveSocietaId(tenantId, mnContext) { if (mnContext && MN_CONTEXT_MAP[mnContext]) return MN_CONTEXT_MAP[mnContext]; if (tenantId && TENANT_MAP[tenantId]) return TENANT_MAP[tenantId]; return "global"; }
function parseIndirizzo(raw) { const match = raw.match(/^(.+?),?\s*(\d{5})?\s+(.+?)(?:\s*\((\w+)\))?$/); if (match) return { via: match[1]?.trim() || raw, cap: match[2] || "", comune: match[3]?.trim() || "", provincia: match[4] || "", nazione_id: "IT" }; return { via: raw, cap: "", comune: "", provincia: "", nazione_id: "IT" }; }
function translateFieldName(field) { const map = { "dati_partenza.rifiuto.stato_fisico": "Stato fisico rifiuto", "num_iscr_sito": "Numero iscrizione sito" }; return map[field] || field; }
export async function checkRentriHealth() { try { const res = await inviaOperazioneRentri({ cliente: "global", tipo_operazione: "LISTA_BLOCCHI", payload: {} }); return { ok: res.success, url: "VPS Proxy", status: res.status, body: res.success ? "OK" : (res.error || "Error") }; } catch (err) { return { ok: false, url: "VPS Proxy", status: 0, body: err.message || String(err) }; } }
export async function inviaFirmaRentri(payload) { const cliente = payload.societaId.toLowerCase(); const res = await emissioneFir(cliente, payload.payloadFir); if (res.success) { const root = res.data || {}; const firId = root.firId || root.numero_fir || root.fir_id || ""; return { ...root, numero_fir: firId, firId, pdf_content: root.pdf_content || root.pdfContent || undefined, qr_code: root.qr_code || root.qrCodeBytes || root.qrCode || undefined }; } const errData = res.data || {}; const modelState = errData?.model_state || {}; const modelErrors = Object.entries(modelState).map(([field, msgs]) => `${translateFieldName(field)}: ${Array.isArray(msgs) ? msgs.join(", ") : msgs}`).join("; "); throw new Error(modelErrors || res.error || errData?.error || `Errore server (${res.status})`); }
export async function getRentriPdf(company, firId) { const res = await scaricaPdfLotto(company.toLowerCase(), firId, "1"); const root = res.data || {}; if (!res.success) throw new Error(res.error || `Errore server (${res.status})`); return { ...root, qrCode: root.qrCode || root.qr_code || undefined, pdfBase64: root.pdfBase64 || root.pdf_base64 || root.pdf_content || undefined, pdfUrl: root.pdfUrl || root.pdf_url || undefined }; }
export async function chiudiFirRentri(payload) { const firPayload = { dati_arrivo: { numero_fir: payload.numero_fir, data_ora_arrivo: payload.data_arrivo || new Date().toISOString(), destinatario: { denominazione: payload.destinatario_denominazione || "", codice_fiscale: payload.destinatario_codice_fiscale || "", indirizzo: parseIndirizzo(payload.destinatario_indirizzo || ""), autorizzazione: { tipo: payload.destinatario_tipo_aut || "AIA", numero: payload.destinatario_numero_aut || "" } }, accettazione: { accettato: true, quantita_ricevuta: { valore: payload.peso_accettato, unita_misura: payload.unita_misura || "kg" } } } }; const res = await firmaRicezione("multy", firPayload); if (!res.success) throw new Error(res.error || `Errore server (${res.status})`); return res.data || {}; }
export async function richiediNuoviNumeri(company, quantity = 5) { const res = await richiestaVidimazione(company.toLowerCase(), quantity); if (!res.success) throw new Error(res.error || `Errore server (${res.status})`); const data = res.data || {}; let numeri = []; if (Array.isArray(data.numeri)) numeri = data.numeri; else if (typeof data.firNumber === "string") numeri = [data.firNumber]; return { ...data, numeri }; }
export function getRentriPdfUrl() { return ""; }
export function getRentriXfirUrl() { return ""; }
export function getRentriQrUrl() { return ""; }
