import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Componente outbox email Global Reco (storico inviate)
import { useState } from "react";
import { useGlobalOutbox } from "@/hooks/useGlobalEmail";
import { format } from "date-fns";
export function GlobalEmailOutbox() {
    const [filter, setFilter] = useState("");
    const { data: emails, isLoading } = useGlobalOutbox(filter || undefined);
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-sm font-semibold text-foreground uppercase tracking-wider", children: "Email Inviate" }), _jsx("div", { className: "flex gap-1", children: ["", "automatica", "manuale"].map((cat) => (_jsx("button", { onClick: () => setFilter(cat), className: `px-3 py-1 rounded-full text-xs transition-colors ${filter === cat ? "bg-primary/20 text-primary" : "bg-secondary/30 text-muted-foreground hover:text-foreground"}`, children: cat === "" ? "Tutte" : cat === "automatica" ? "Automatiche" : "Manuali" }, cat))) })] }), isLoading && _jsx("p", { className: "text-sm text-muted-foreground", children: "Caricamento..." }), _jsxs("div", { className: "space-y-2 max-h-[500px] overflow-y-auto", children: [(emails || []).map((e) => (_jsxs("div", { className: "p-3 rounded-lg bg-card/60 border border-border/20 text-sm", children: [_jsxs("div", { className: "flex justify-between text-xs text-muted-foreground mb-1", children: [_jsxs("span", { className: "truncate max-w-[50%]", children: ["\u2192 ", e.to_address] }), _jsx("span", { children: format(new Date(e.sent_at), "dd/MM/yy HH:mm") })] }), _jsx("p", { className: "text-foreground text-xs font-medium truncate", children: e.subject || "(nessun oggetto)" }), _jsxs("div", { className: "flex gap-2 mt-1", children: [_jsx("span", { className: `text-xs px-2 py-0.5 rounded-full ${e.status === "sent" ? "bg-emerald-500/20 text-emerald-400" : "bg-red-500/20 text-red-400"}`, children: e.status }), _jsx("span", { className: "text-xs px-2 py-0.5 rounded-full bg-secondary/30 text-muted-foreground", children: e.category })] }), e.error_message && _jsx("p", { className: "text-xs text-red-400 mt-1", children: e.error_message })] }, e.id))), !isLoading && (!emails || emails.length === 0) && (_jsx("p", { className: "text-muted-foreground text-sm", children: "Nessuna email inviata" }))] })] }));
}
