import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle2, XCircle, ShieldCheck } from "lucide-react";
/** Banner esito: messaggio leggibile + dettagli tecnici collassati (mai segreti). */
export function RentriResultBanner({ result }) {
    if (!result)
        return null;
    const ok = result.success;
    return (_jsxs("div", { "data-testid": "rentri-result", className: `mt-4 rounded-xl p-4 text-sm border ${ok ? "bg-primary/10 border-primary/30" : "bg-destructive/10 border-destructive/30"}`, children: [_jsxs("div", { className: "flex items-center gap-2 font-semibold", children: [result.mode === "dry_run"
                        ? _jsx(ShieldCheck, { size: 16, className: "text-primary" })
                        : ok
                            ? _jsx(CheckCircle2, { size: 16, className: "text-primary" })
                            : _jsx(XCircle, { size: 16, className: "text-destructive" }), _jsxs("span", { children: [result.mode === "dry_run" && (ok ? "Configurazione valida — nessun invio effettuato" : "Configurazione incompleta — nessun invio effettuato"), result.mode !== "dry_run" && (ok ? "Operazione completata" : "Operazione non riuscita")] }), _jsxs("span", { className: "ml-auto text-xs text-muted-foreground", children: ["HTTP ", result.status || "—", " \u00B7 ", result.errorCode ?? "OK"] })] }), _jsx("p", { className: "mt-2 text-muted-foreground", children: result.userMessage }), result.preview && (_jsxs("dl", { className: "mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-muted-foreground", children: [_jsx("dt", { children: "Cliente" }), _jsx("dd", { className: "text-foreground", children: result.preview.cliente }), _jsx("dt", { children: "Chiave configurazione" }), _jsx("dd", { className: "text-foreground", children: result.preview.config_key }), _jsx("dt", { children: "Metodo / Path" }), _jsxs("dd", { className: "text-foreground break-all", children: [result.preview.rentri_method, " ", result.preview.rentri_path] }), _jsx("dt", { children: "Iscrizione sito" }), _jsx("dd", { className: "text-foreground", children: result.preview.has_num_iscr_sito ? "configurata" : "mancante" }), _jsx("dt", { children: "Registro" }), _jsx("dd", { className: "text-foreground", children: result.preview.has_registry_id ? "configurato" : "mancante" }), _jsx("dt", { children: "Blocchi" }), _jsx("dd", { className: "text-foreground", children: result.preview.blocchi_configurati }), _jsx("dt", { children: "Chiave bridge" }), _jsx("dd", { className: "text-foreground", children: result.preview.bridge_key_configurata ? "presente sul server" : "mancante" })] })), (result.error || result.errori?.length) && (_jsxs("details", { className: "mt-3", children: [_jsx("summary", { className: "cursor-pointer text-xs text-muted-foreground", children: "Dettagli tecnici" }), _jsx("pre", { className: "mt-2 text-xs font-mono whitespace-pre-wrap break-all max-h-48 overflow-auto text-muted-foreground", children: [result.error, ...(result.errori ?? [])].filter(Boolean).join("\n") })] }))] }));
}
export default RentriResultBanner;
