import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route, Navigate, useLocation } from "react-router-dom";
import { AuthProvider } from "@/hooks/useAuth";
import { PresenceProvider } from "@/components/providers/PresenceProvider";
import { CallProvider } from "@/contexts/CallContext";
import { FormBridgeProvider } from "@/contexts/FormBridgeContext";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { RoleBasedRedirect } from "@/components/RoleBasedRedirect";
import { ZoliDarkLemonWidget } from "@/components/ai/ZoliDarkLemonWidget";
import { CallManager } from "@/components/calls/CallManager";
import { GlobalNotificationBell } from "@/components/notifications/GlobalNotificationBell";
// Lazy-loaded pages
const AuthPage = React.lazy(() => import("./pages/AuthPage"));
const MNAuthPage = React.lazy(() => import("./pages/MNAuthPage"));
const MNAdminAuthPage = React.lazy(() => import("./pages/MNAdminAuthPage"));
const SuperAdminAuthPage = React.lazy(() => import("./pages/SuperAdminAuthPage"));
const SuperAdminDashboard = React.lazy(() => import("./pages/SuperAdminDashboard"));
const SuperAdminFormEditor = React.lazy(() => import("./pages/SuperAdminFormEditor"));
const SocialPage = React.lazy(() => import("./pages/SocialPage"));
const SocialGuestAuthPage = React.lazy(() => import("./pages/SocialGuestAuthPage"));
const SocialAIPage = React.lazy(() => import("./pages/SocialAIPage"));
const MobileAppPage = React.lazy(() => import("./pages/MobileAppPage"));
const CronologiaFIRPage = React.lazy(() => import("./pages/CronologiaFIRPage"));
const GPSPage = React.lazy(() => import("./pages/GPSPage"));
const AIAssistantPage = React.lazy(() => import("./pages/AIAssistantPage"));
const ComunicazioniPage = React.lazy(() => import("./pages/ComunicazioniPage"));
const ZoliMessagesPage = React.lazy(() => import("./pages/ZoliMessagesPage"));
const ProfiloPage = React.lazy(() => import("./pages/ProfiloPage"));
const GuidaPage = React.lazy(() => import("./pages/GuidaPage"));
const AppPhonePage = React.lazy(() => import("./pages/AppPhonePage"));
const ProfileSetupPage = React.lazy(() => import("./pages/ProfileSetupPage"));
const DashboardPage = React.lazy(() => import("./pages/admin/DashboardPage"));
const RENTRIPage = React.lazy(() => import("./pages/admin/RENTRIPage"));
const PersonalePage = React.lazy(() => import("./pages/admin/PersonalePage"));
const RegistroFIRPage = React.lazy(() => import("./pages/admin/RegistroFIRPage"));
const CallReportsPage = React.lazy(() => import("./pages/admin/CallReportsPage"));
const AdminMessagesPage = React.lazy(() => import("./pages/admin/AdminMessagesPage"));
const ZoliDarkLemonPage = React.lazy(() => import("./pages/admin/ZoliDarkLemonPage"));
const FormulariPage = React.lazy(() => import("./pages/admin/FormulariPage"));
const GestioneFIRPage = React.lazy(() => import("./pages/admin/GestioneFIRPage"));
const GPSFlottaPage = React.lazy(() => import("./pages/admin/GPSFlottaPage"));
const FatturazionePage = React.lazy(() => import("./pages/admin/FatturazionePage"));
const IntermediazionePage = React.lazy(() => import("./pages/admin/IntermediazionePage"));
const PhonePage = React.lazy(() => import("./pages/admin/PhonePage"));
const SMSPage = React.lazy(() => import("./pages/admin/SMSPage"));
const WhatsAppPage = React.lazy(() => import("./pages/admin/WhatsAppPage"));
const EmailPage = React.lazy(() => import("./pages/admin/EmailPage"));
const GlobalEmailPage = React.lazy(() => import("./pages/admin/GlobalEmailPage"));
const RubricaPage = React.lazy(() => import("./pages/admin/RubricaPage"));
const SystemPromptPage = React.lazy(() => import("./pages/admin/SystemPromptPage"));
const SocialGuestsPage = React.lazy(() => import("./pages/admin/SocialGuestsPage"));
const MNDashboardPage = React.lazy(() => import("./pages/multynijol/MNDashboardPage"));
const MNContextDashboardPage = React.lazy(() => import("./pages/multynijol/MNContextDashboardPage"));
const MNRegistroFIRPage = React.lazy(() => import("./pages/multynijol/MNRegistroFIRPage"));
const MNRENTRIPage = React.lazy(() => import("./pages/multynijol/MNRENTRIPage"));
const MNTrasportatoriPage = React.lazy(() => import("./pages/multynijol/MNTrasportatoriPage"));
const MNTransporterAppPage = React.lazy(() => import("./pages/multynijol/MNTransporterAppPage"));
const MNPersonalePage = React.lazy(() => import("./pages/multynijol/MNPersonalePage"));
const MNMessagesPage = React.lazy(() => import("./pages/multynijol/MNMessagesPage"));
const MNCallReportsPage = React.lazy(() => import("./pages/multynijol/MNCallReportsPage"));
const MNMagazzinoPage = React.lazy(() => import("./pages/multynijol/MNMagazzinoPage"));
const MNConferimentiPage = React.lazy(() => import("./pages/multynijol/MNConferimentiPage"));
const MNImpiantiPage = React.lazy(() => import("./pages/multynijol/MNImpiantiPage"));
const MNImpiantoProduttorePage = React.lazy(() => import("./pages/multynijol/MNImpiantoProduttorePage"));
const MNImpiantoDestinatarioPage = React.lazy(() => import("./pages/multynijol/MNImpiantoDestinatarioPage"));
const MNPagamentiPage = React.lazy(() => import("./pages/multynijol/MNPagamentiPage"));
const MNRegistroKgPage = React.lazy(() => import("./pages/multynijol/MNRegistroKgPage"));
const MNFirDigitaliPage = React.lazy(() => import("./pages/multynijol/MNFirDigitaliPage"));
const MNMultyprogetAppPage = React.lazy(() => import("./pages/multynijol/MNMultyprogetAppPage"));
const MNNiyolAppPage = React.lazy(() => import("./pages/multynijol/MNNiyolAppPage"));
const MNFormulariPage = React.lazy(() => import("./pages/multynijol/MNFormulariPage"));
const MNGestioneFIRPage = React.lazy(() => import("./pages/multynijol/MNGestioneFIRPage"));
const MNGPSFlottaPage = React.lazy(() => import("./pages/multynijol/MNGPSFlottaPage"));
const MNZoliDarkLemonPage = React.lazy(() => import("./pages/multynijol/MNZoliDarkLemonPage"));
const MNFatturazionePage = React.lazy(() => import("./pages/multynijol/MNFatturazionePage"));
const MNIntermediazionePage = React.lazy(() => import("./pages/multynijol/MNIntermediazionePage"));
const MNPhonePage = React.lazy(() => import("./pages/multynijol/MNPhonePage"));
const MNSMSPage = React.lazy(() => import("./pages/multynijol/MNSMSPage"));
const MNWhatsAppPage = React.lazy(() => import("./pages/multynijol/MNWhatsAppPage"));
const MNEmailPage = React.lazy(() => import("./pages/multynijol/MNEmailPage"));
const MNRubricaPage = React.lazy(() => import("./pages/multynijol/MNRubricaPage"));
const MNAnagraficaPrivatiPage = React.lazy(() => import("./pages/multynijol/MNAnagraficaPrivatiPage"));
const MNStoricoRicevutePage = React.lazy(() => import("./pages/multynijol/MNStoricoRicevutePage"));
// Dragon Rifiuti 2 pages
const DragonRegistroPage = React.lazy(() => import("./pages/dragon/DragonRegistroPage"));
const DragonMagazzinoPage = React.lazy(() => import("./pages/dragon/DragonMagazzinoPage"));
const DragonCantieriPage = React.lazy(() => import("./pages/dragon/DragonCantieriPage"));
const DragonArticoliPage = React.lazy(() => import("./pages/dragon/DragonArticoliPage"));
const DragonDocumentiPage = React.lazy(() => import("./pages/dragon/DragonDocumentiPage"));
const DragonCerniteModelliPage = React.lazy(() => import("./pages/dragon/DragonCerniteModelliPage"));
const DragonCerniteBatchPage = React.lazy(() => import("./pages/dragon/DragonCerniteBatchPage"));
const DragonAuditPage = React.lazy(() => import("./pages/dragon/DragonAuditPage"));
const DragonCaricoScaricoPage = React.lazy(() => import("./pages/dragon/DragonCaricoScaricoPage"));
const DragonScaricoCumulativoPage = React.lazy(() => import("./pages/dragon/DragonScaricoCumulativoPage"));
const MNSystemPromptPage = React.lazy(() => import("./pages/multynijol/MNSystemPromptPage"));
const MNDevDashboardPage = React.lazy(() => import("./pages/multynijol/MNDevDashboardPage.tsx"));
const MNAreeRiservateImpiantiPage = React.lazy(() => import("./pages/multynijol/MNAreeRiservateImpiantiPage"));
const ImpiantoLoginPage = React.lazy(() => import("./pages/ImpiantoLoginPage"));
const ImpiantoDashboardPage = React.lazy(() => import("./pages/ImpiantoDashboardPage"));
const AdminAreeRiservateGlobalPage = React.lazy(() => import("./pages/admin/AdminAreeRiservateGlobalPage"));
const MNAppCronologiaPage = React.lazy(() => import("./pages/multynijol/MNAppCronologiaPage"));
const MNAppGPSPage = React.lazy(() => import("./pages/multynijol/MNAppGPSPage"));
const MNAppAIPage = React.lazy(() => import("./pages/multynijol/MNAppAIPage"));
const MNAppComunicazioniPage = React.lazy(() => import("./pages/multynijol/MNAppComunicazioniPage"));
const MNAppPhonePage = React.lazy(() => import("./pages/multynijol/MNAppPhonePage"));
const MNAppProfiloPage = React.lazy(() => import("./pages/multynijol/MNAppProfiloPage"));
const MNAppGuidaPage = React.lazy(() => import("./pages/multynijol/MNAppGuidaPage"));
const MNAppModuloAlternativoPage = React.lazy(() => import("./pages/multynijol/MNAppModuloAlternativoPage"));
const ModuloAlternativoPage = React.lazy(() => import("./pages/ModuloAlternativoPage"));
const GuidaCompletaPage = React.lazy(() => import("./pages/GuidaCompletaPage"));
const AppuntamentoPersonalePage = React.lazy(() => import("./pages/AppuntamentoPersonalePage"));
const NotFound = React.lazy(() => import("./pages/NotFound"));
const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 1 } } });
function LoadingScreen() {
    return (_jsx("div", { className: "min-h-screen bg-background flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Caricamento..." })] }) }));
}
function AdminOverlays() {
    const location = useLocation();
    const isAdminRoute = location.pathname.startsWith("/admin") || location.pathname.startsWith("/mn/admin");
    if (!isAdminRoute)
        return null;
    return _jsx(ZoliDarkLemonWidget, {});
}
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsx(PresenceProvider, { children: _jsx(CallProvider, { children: _jsxs(FormBridgeProvider, { children: [_jsx(Toaster, { position: "top-right", theme: "dark" }), _jsx(CallManager, {}), _jsx(GlobalNotificationBell, {}), _jsx(Suspense, { fallback: _jsx(LoadingScreen, {}), children: _jsxs(Routes, { children: [_jsx(Route, { path: "/auth", element: _jsx(AuthPage, {}) }), _jsx(Route, { path: "/mn", element: _jsx(MNAuthPage, {}) }), _jsx(Route, { path: "/ni", element: _jsx(MNAuthPage, {}) }), _jsx(Route, { path: "/mn/auth", element: _jsx(MNAuthPage, {}) }), _jsx(Route, { path: "/mn/auth/:context", element: _jsx(MNAuthPage, {}) }), _jsx(Route, { path: "/adminmn", element: _jsx(MNAdminAuthPage, {}) }), _jsx(Route, { path: "/superadmin", element: _jsx(SuperAdminAuthPage, {}) }), _jsx(Route, { path: "/super", element: _jsx(ProtectedRoute, { children: _jsx(SuperAdminDashboard, {}) }) }), _jsx(Route, { path: "/super/form-editor", element: _jsx(ProtectedRoute, { children: _jsx(SuperAdminFormEditor, {}) }) }), _jsx(Route, { path: "/super/modulo-alternativo", element: _jsx(ProtectedRoute, { children: _jsx(ModuloAlternativoPage, {}) }) }), _jsx(Route, { path: "/social", element: _jsx(ProtectedRoute, { children: _jsx(SocialPage, {}) }) }), _jsx(Route, { path: "/social/ai", element: _jsx(ProtectedRoute, { children: _jsx(SocialAIPage, {}) }) }), _jsx(Route, { path: "/social/guest", element: _jsx(SocialGuestAuthPage, {}) }), _jsx(Route, { path: "/appuntamento-personale", element: _jsx(AppuntamentoPersonalePage, {}) }), _jsx(Route, { path: "/", element: _jsx(RoleBasedRedirect, {}) }), _jsx(Route, { path: "/profile/setup", element: _jsx(ProtectedRoute, { children: _jsx(ProfileSetupPage, {}) }) }), _jsx(Route, { path: "/app", element: _jsx(ProtectedRoute, { children: _jsx(MobileAppPage, {}) }) }), _jsx(Route, { path: "/app/cronologia", element: _jsx(ProtectedRoute, { children: _jsx(CronologiaFIRPage, {}) }) }), _jsx(Route, { path: "/app/gps", element: _jsx(ProtectedRoute, { children: _jsx(GPSPage, {}) }) }), _jsx(Route, { path: "/app/ai", element: _jsx(ProtectedRoute, { children: _jsx(AIAssistantPage, {}) }) }), _jsx(Route, { path: "/app/telefono", element: _jsx(ProtectedRoute, { children: _jsx(AppPhonePage, {}) }) }), _jsx(Route, { path: "/app/comunicazioni", element: _jsx(ProtectedRoute, { children: _jsx(ComunicazioniPage, {}) }) }), _jsx(Route, { path: "/app/profilo", element: _jsx(ProtectedRoute, { children: _jsx(ProfiloPage, {}) }) }), _jsx(Route, { path: "/app/guida", element: _jsx(ProtectedRoute, { children: _jsx(GuidaCompletaPage, {}) }) }), _jsx(Route, { path: "/app/modulo-alternativo", element: _jsx(ProtectedRoute, { children: _jsx(MNAppModuloAlternativoPage, {}) }) }), _jsx(Route, { path: "/guida-completa", element: _jsx(ProtectedRoute, { children: _jsx(GuidaCompletaPage, {}) }) }), _jsx(Route, { path: "/admin", element: _jsx(ProtectedRoute, { children: _jsx(DashboardPage, {}) }) }), _jsx(Route, { path: "/admin/rentri", element: _jsx(ProtectedRoute, { children: _jsx(RENTRIPage, {}) }) }), _jsx(Route, { path: "/admin/personale", element: _jsx(ProtectedRoute, { children: _jsx(PersonalePage, {}) }) }), _jsx(Route, { path: "/admin/registro", element: _jsx(ProtectedRoute, { children: _jsx(RegistroFIRPage, {}) }) }), _jsx(Route, { path: "/admin/chiamate", element: _jsx(ProtectedRoute, { children: _jsx(CallReportsPage, {}) }) }), _jsx(Route, { path: "/admin/messaggi", element: _jsx(ProtectedRoute, { children: _jsx(AdminMessagesPage, {}) }) }), _jsx(Route, { path: "/admin/messaggi/:partnerId", element: _jsx(ProtectedRoute, { children: _jsx(AdminMessagesPage, {}) }) }), _jsx(Route, { path: "/admin/zoli-dark-lemon", element: _jsx(ProtectedRoute, { children: _jsx(ZoliDarkLemonPage, {}) }) }), _jsx(Route, { path: "/admin/formulari", element: _jsx(ProtectedRoute, { children: _jsx(FormulariPage, {}) }) }), _jsx(Route, { path: "/admin/gestione-fir", element: _jsx(ProtectedRoute, { children: _jsx(GestioneFIRPage, {}) }) }), _jsx(Route, { path: "/admin/gps", element: _jsx(ProtectedRoute, { children: _jsx(GPSFlottaPage, {}) }) }), _jsx(Route, { path: "/admin/fatturazione", element: _jsx(ProtectedRoute, { children: _jsx(FatturazionePage, {}) }) }), _jsx(Route, { path: "/admin/intermediazione", element: _jsx(ProtectedRoute, { children: _jsx(IntermediazionePage, {}) }) }), _jsx(Route, { path: "/admin/telefono", element: _jsx(ProtectedRoute, { children: _jsx(PhonePage, {}) }) }), _jsx(Route, { path: "/admin/sms", element: _jsx(ProtectedRoute, { children: _jsx(SMSPage, {}) }) }), _jsx(Route, { path: "/admin/whatsapp", element: _jsx(ProtectedRoute, { children: _jsx(WhatsAppPage, {}) }) }), _jsx(Route, { path: "/admin/email", element: _jsx(ProtectedRoute, { children: _jsx(EmailPage, {}) }) }), _jsx(Route, { path: "/admin/email-global", element: _jsx(ProtectedRoute, { children: _jsx(GlobalEmailPage, {}) }) }), _jsx(Route, { path: "/admin/rubrica", element: _jsx(ProtectedRoute, { children: _jsx(RubricaPage, {}) }) }), _jsx(Route, { path: "/admin/system-prompt", element: _jsx(ProtectedRoute, { children: _jsx(SystemPromptPage, {}) }) }), _jsx(Route, { path: "/admin/social-guests", element: _jsx(ProtectedRoute, { children: _jsx(SocialGuestsPage, {}) }) }), _jsx(Route, { path: "/admin/modulo-alternativo", element: _jsx(ProtectedRoute, { children: _jsx(ModuloAlternativoPage, {}) }) }), _jsx(Route, { path: "/admin/aree-riservate-impianti", element: _jsx(ProtectedRoute, { children: _jsx(AdminAreeRiservateGlobalPage, {}) }) }), _jsx(Route, { path: "/area-impianto/:tenant", element: _jsx(ImpiantoLoginPage, {}) }), _jsx(Route, { path: "/area-impianto/:tenant/dashboard", element: _jsx(ImpiantoDashboardPage, {}) }), _jsx(Route, { path: "/mn/admin", element: _jsx(ProtectedRoute, { children: _jsx(MNDashboardPage, {}) }) }), _jsx(Route, { path: "/mn/admin/dev-multyproget", element: _jsx(ProtectedRoute, { children: _jsx(MNDevDashboardPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context", element: _jsx(ProtectedRoute, { children: _jsx(MNContextDashboardPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/registro", element: _jsx(ProtectedRoute, { children: _jsx(MNRegistroFIRPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/rentri", element: _jsx(ProtectedRoute, { children: _jsx(MNRENTRIPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/trasportatori", element: _jsx(ProtectedRoute, { children: _jsx(MNTrasportatoriPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/transporter-app", element: _jsx(ProtectedRoute, { children: _jsx(MNTransporterAppPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/personale", element: _jsx(ProtectedRoute, { children: _jsx(MNPersonalePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/messaggi", element: _jsx(ProtectedRoute, { children: _jsx(MNMessagesPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/messaggi/:partnerId", element: _jsx(ProtectedRoute, { children: _jsx(MNMessagesPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/chiamate", element: _jsx(ProtectedRoute, { children: _jsx(MNCallReportsPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/impianto/privati", element: _jsx(ProtectedRoute, { children: _jsx(MNMagazzinoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/impianto/produttore", element: _jsx(ProtectedRoute, { children: _jsx(MNImpiantoProduttorePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/impianto/destinatario", element: _jsx(ProtectedRoute, { children: _jsx(MNImpiantoDestinatarioPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/magazzino", element: _jsx(ProtectedRoute, { children: _jsx(MNMagazzinoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/conferimenti", element: _jsx(ProtectedRoute, { children: _jsx(MNConferimentiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/impianti", element: _jsx(ProtectedRoute, { children: _jsx(MNImpiantiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/pagamenti", element: _jsx(ProtectedRoute, { children: _jsx(MNPagamentiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/registro-kg", element: _jsx(ProtectedRoute, { children: _jsx(MNRegistroKgPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/fir-digitali", element: _jsx(ProtectedRoute, { children: _jsx(MNFirDigitaliPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/formulari", element: _jsx(ProtectedRoute, { children: _jsx(MNFormulariPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/gestione-fir", element: _jsx(ProtectedRoute, { children: _jsx(MNGestioneFIRPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/gps", element: _jsx(ProtectedRoute, { children: _jsx(MNGPSFlottaPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/zoli-dark-lemon", element: _jsx(ProtectedRoute, { children: _jsx(MNZoliDarkLemonPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/fatturazione", element: _jsx(ProtectedRoute, { children: _jsx(MNFatturazionePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/intermediazione", element: _jsx(ProtectedRoute, { children: _jsx(MNIntermediazionePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/telefono", element: _jsx(ProtectedRoute, { children: _jsx(MNPhonePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/sms", element: _jsx(ProtectedRoute, { children: _jsx(MNSMSPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/whatsapp", element: _jsx(ProtectedRoute, { children: _jsx(MNWhatsAppPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/email", element: _jsx(ProtectedRoute, { children: _jsx(MNEmailPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/rubrica", element: _jsx(ProtectedRoute, { children: _jsx(MNRubricaPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/anagrafica/privati", element: _jsx(ProtectedRoute, { children: _jsx(MNAnagraficaPrivatiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/storico-ricevute", element: _jsx(ProtectedRoute, { children: _jsx(MNStoricoRicevutePage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/system-prompt", element: _jsx(ProtectedRoute, { children: _jsx(MNSystemPromptPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/modulo-alternativo", element: _jsx(ProtectedRoute, { children: _jsx(ModuloAlternativoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/aree-riservate-impianti", element: _jsx(ProtectedRoute, { children: _jsx(MNAreeRiservateImpiantiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/registro", element: _jsx(ProtectedRoute, { children: _jsx(DragonRegistroPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/magazzino", element: _jsx(ProtectedRoute, { children: _jsx(DragonMagazzinoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/cantieri", element: _jsx(ProtectedRoute, { children: _jsx(DragonCantieriPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/articoli", element: _jsx(ProtectedRoute, { children: _jsx(DragonArticoliPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/documenti", element: _jsx(ProtectedRoute, { children: _jsx(DragonDocumentiPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/cernite/modelli", element: _jsx(ProtectedRoute, { children: _jsx(DragonCerniteModelliPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/audit", element: _jsx(ProtectedRoute, { children: _jsx(DragonAuditPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/registro/carico-scarico", element: _jsx(ProtectedRoute, { children: _jsx(DragonCaricoScaricoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/registro/scarico-cumulativo", element: _jsx(ProtectedRoute, { children: _jsx(DragonScaricoCumulativoPage, {}) }) }), _jsx(Route, { path: "/mn/admin/:context/dragon/cernite/batch", element: _jsx(ProtectedRoute, { children: _jsx(DragonCerniteBatchPage, {}) }) }), _jsx(Route, { path: "/mn/app/multyproget", element: _jsx(MNMultyprogetAppPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/cronologia", element: _jsx(MNAppCronologiaPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/gps", element: _jsx(MNAppGPSPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/ai", element: _jsx(MNAppAIPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/telefono", element: _jsx(MNAppPhonePage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/comunicazioni", element: _jsx(MNAppComunicazioniPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/profilo", element: _jsx(MNAppProfiloPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/guida", element: _jsx(MNAppGuidaPage, {}) }), _jsx(Route, { path: "/mn/app/multyproget/modulo-alternativo", element: _jsx(MNAppModuloAlternativoPage, {}) }), _jsx(Route, { path: "/mn/app/niyol", element: _jsx(MNNiyolAppPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/cronologia", element: _jsx(MNAppCronologiaPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/gps", element: _jsx(MNAppGPSPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/ai", element: _jsx(MNAppAIPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/telefono", element: _jsx(MNAppPhonePage, {}) }), _jsx(Route, { path: "/mn/app/niyol/comunicazioni", element: _jsx(MNAppComunicazioniPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/profilo", element: _jsx(MNAppProfiloPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/guida", element: _jsx(MNAppGuidaPage, {}) }), _jsx(Route, { path: "/mn/app/niyol/modulo-alternativo", element: _jsx(MNAppModuloAlternativoPage, {}) }), _jsx(Route, { path: "/mn/app/messages", element: _jsx(ZoliMessagesPage, {}) }), _jsx(Route, { path: "/carica-fir", element: _jsx(Navigate, { to: "/app", replace: true }) }), _jsx(Route, { path: "/transazioni", element: _jsx(Navigate, { to: "/app/cronologia", replace: true }) }), _jsx(Route, { path: "/massive", element: _jsx(Navigate, { to: "/admin", replace: true }) }), _jsx(Route, { path: "/bridge", element: _jsx(Navigate, { to: "/admin", replace: true }) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }) }), _jsx(AdminOverlays, {})] }) }) }) }) }) }));
export default App;
