export const Constants = {
    public: {
        Enums: {
            app_role: ["admin", "user"],
            call_status: ["ringing", "answered", "ended", "missed", "ai_fallback"],
            call_type: ["audio", "video"],
            dragon_adjustment_type: ["POSITIVE", "NEGATIVE"],
            dragon_audit_action: [
                "CREATE",
                "UPDATE",
                "SOFT_DELETE",
                "RESTORE",
                "CONFIRM",
                "CANCEL",
                "ADJUST",
            ],
            dragon_batch_status: ["BOZZA", "CONFERMATA", "ANNULLATA"],
            dragon_cause_direction: ["IN", "OUT", "TRANSFORM", "ADJUST"],
            dragon_cause_scope: ["REGISTER", "STOCK", "BOTH"],
            dragon_document_type: [
                "FIR",
                "DDT_IN",
                "DDT_OUT",
                "FORMULARIO_MODELLO",
                "ALTRO",
            ],
            dragon_item_type: ["WASTE_CER", "MPS", "MATERIAL"],
            dragon_movement_status: [
                "BOZZA",
                "CONSOLIDATO",
                "STAMPATO",
                "DA_NON_STAMPARE",
                "DA_NON_INVIARE_RENTRI",
                "INVIATO_RENTRI",
            ],
            dragon_movement_type: ["CARICO", "SCARICO"],
            dragon_quantity_mode: ["PERCENT", "FIXED"],
            dragon_sign: ["PLUS", "MINUS"],
            dragon_site_activity: [
                "ND",
                "MANUTENZIONE",
                "ASSISTENZA_SANITARIA",
                "CANTIERE_TEMPORANEO_MOBILE",
                "BONIFICA_AMIANTO",
            ],
            dragon_source_context: ["UL", "FUORI_UL"],
            dragon_stock_sign: ["PLUS", "MINUS", "NONE"],
            dragon_subject_type: [
                "PRODUTTORE",
                "DESTINATARIO",
                "TRASPORTATORE",
                "INTERMEDIARIO",
            ],
            dragon_warehouse_scope: ["WASTE", "MPS"],
            dragon_weight_status: ["DEFINITIVO", "DA_VERIFICARE_A_DESTINO"],
            fir_stato: [
                "DRAFT",
                "READY_TO_SEND",
                "ACTIVE",
                "IN_TRANSIT",
                "DELIVERED_PENDING_ACCEPTANCE",
                "CLOSED",
                "SENT_TO_RENTRI_DATA",
            ],
            membership_role: ["owner", "admin", "operator", "viewer"],
            org_role_rentri: [
                "produttore",
                "trasportatore",
                "destinatario",
                "intermediario",
            ],
            presence_status: ["online", "offline", "busy", "away"],
            register_movement_type: ["CARICO", "SCARICO"],
            register_send_status: ["PENDING", "SENT"],
        },
    },
};
